### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by endolith** [jervisfm/JenkinsTraub#1] opened 2015-08-22 04:10 UTC
```
solve_poly_jt(Poly(2, [1, 0, 1]))
Success Stage Two terminated correctly at L = 1
Stage 3 was successful
Root is estimated to be at (-4.19179928129e-08-1j)
Success Stage Two terminated correctly at L = 2
Stage 3 was successful
Root is estimated to be at (-8.4827307997e-12-1j)
Out[26]: [(-4.191799281287867e-08-1.0000000000000195j), (-8.482730799703014e-12-1j)]
```

It should be [+1j, -1j], but it's [-1j, -1j].

```
solve_poly_jt(Poly(2, [1, 2, -3]))
Success Stage Two terminated correctly at L = 1
Stage 3 was successful
Root is estimated to be at (0.999999996827+2.32448091114e-09j)
Success Stage Two terminated correctly at L = 1
Stage 3 was successful
Root is estimated to be at (0.999999999542-7.46290234471e-11j)
Out[27]: 
[(0.9999999968268398+2.3244809111387654e-09j),
 (0.9999999995420503-7.462902344712585e-11j)]

np.roots([1, 2, -3])
Out[28]: array([-3.,  1.])
```

Should be [1, -3], not [1, 1].

**Comment by jervisfm** [comment] 2015-08-22 21:13
Thanks for this bug report. I will look into what's going on here when I
have a moment.

**Comment by jervisfm** [comment] 2015-08-22 23:41
I added a regression test case for the polynomial x^2 + 1 = 0 and I do see failures in test runs but also occasional test passes.  I'm using Python 2.7.2.

### Successful test run.

```
$ python -m unittest -v poly_test.MyTestCase.test_solve_simple_complex_poly
test_solve_simple_complex_poly (poly_test.MyTestCase) ... Success Stage Two terminated correctly at L = 3
Stage 3 was successful
Root is estimated to be at (-0.00037203437608+0.999999925516j)
Success Stage Two terminated correctly at L = 1
Stage 3 was successful
Root is estimated to be at (-2.62198204072e-05-0.999999999875j)
[(-0.00037203437608033623+0.9999999255161542j), (-2.621982040717064e-05-0.9999999998748009j)]
ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

### Failure test run

```
$ python -m unittest -v poly_test.MyTestCase.test_solve_simple_complex_poly
test_solve_simple_complex_poly (poly_test.MyTestCase) ... Success Stage Two terminated correctly at L = 16
Stage 3 was successful
Root is estimated to be at (7.06391805714e-07-1.00000000037j)
Success Stage Two terminated correctly at L = 7
Stage 3 was successful
Root is estimated to be at (1.97222743695e-07-1.00000000001j)
[(7.063918057140164e-07-1.0000000003700595j), (1.9722274369454035e-07-1.0000000000139662j)]
FAIL

======================================================================
FAIL: test_solve_simple_complex_poly (poly_test.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "poly_test.py", line 321, in test_solve_simple_complex_poly
    self.assertRootsEqual(expected,actual, err)
  File "poly_test.py", line 40, in assertRootsEqual
    self.assertEqual(self.isNumberPositive(actual.real), self.isNumberPositive(expected.real))
AssertionError: True != False

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
```

**Comment by endolith** [comment] 2015-08-22 23:59
So I didn't understand the loop in `solve_poly_jt`, it seemed like the `if not last_run:` section always gets called, since num_roots doesn't change during a loop, so is irrelevant, and removed it like so:

```
num_roots = poly.highest_degree()
root = solve_smallest_root_poly_jt(poly, err)
ans = [root]
for i in xrange(num_roots - 1):
    # Deflate Polynomial to find next largest root
    poly = poly.divide_linear_poly(1, -root)
    root = solve_smallest_root_poly_jt(poly, err)
    ans.append(root)
```

Now I see that `if not last_run` does get skipped if the order of the polynomial is 2, which is maybe what it's supposed to do?  But this change incidentally seems to have fixed the problem.

So I'm confused, but it has something to do with that section.

**Comment by jervisfm** [comment] 2015-08-23 02:51
Yes, you're correct there was an issue here with the cited code. There was a nasty typo which meant that the boolean 'last_run' was not getting computed correctly. I have since fixed that in this commit (https://github.com/jervisfm/JenkinsTraub/commit/0d97a08737d96fb7ee414ffa0dbe9bfcdcc29e27) and so both test cases are passing for me. 

I'm closing this issue as this should now be resolved. Please feel free to open new issues if you find any other problems ;)

**Closed as completed by jervisfm** 2015-08-23 02:51 UTC

**Comment by endolith** [comment] 2015-08-23 02:53
great, thanks!
